apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-postgres.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keycloak-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
