{{- if or (eq (toString .Values.automationCreds.enabled) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-server.fullname" . }}-automation-aws
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "6"
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.automationCreds.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.automationCreds.awsSecretAccessKey | quote }}
  KEYCLOAK_ADMIN_USER: {{ .Values.automationCreds.keycloakAdminUser | quote }}
  KEYCLOAK_ADMIN_PASS: {{ .Values.automationCreds.keycloakAdminPass | quote }}
{{- end }}
