{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "api-server.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "api-server.selectorLabels" . | nindent 6 }}
{{- end }}
