apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-server.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | default "" | quote }}
  RABBITMQ_URL: {{ .Values.secrets.rabbitmqUrl | default "" | quote }}
  KEYCLOAK_ISSUER: {{ .Values.secrets.keycloakIssuer | default "" | quote }}
  CONSUL_HTTP_TOKEN: {{ .Values.secrets.consulToken | default "" | quote }}
  VALKEY_URL: {{ .Values.secrets.valkeyUrl | default "" | quote }}
  AUTOMATION_WEBHOOK_URL: {{ .Values.secrets.automationWebhookUrl | default "" | quote }}
  AUTOMATION_AUTH: {{ .Values.secrets.automationAuth | default "" | quote }}
  RDS_ADMIN_URL: {{ .Values.secrets.rdsAdminUrl | default "" | quote }}
  ROLLBAR_ACCESS_TOKEN: {{ .Values.secrets.rollbarAccessToken | default "" | quote }}
  ROLLBAR_HASH_SALT: {{ .Values.secrets.rollbarHashSalt | default "" | quote }}
