apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-server.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  KEYCLOAK_URL: {{ .Values.config.keycloakUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.config.keycloakRealm | quote }}
  CONSUL_HTTP_ADDR: {{ .Values.config.consulAddr | quote }}
