/**
 * Share Routes — Public conversation sharing (no auth required)
 *
 * Two access modes:
 * 1. Public: conversation has share_status='public' → anyone with the link can view
 * 2. Token-protected: share_status='token' → requires ?token= matching stored share_token
 *
 * Token is a simple random hash generated by Rita, not a JWT.
 * Actions Platform requests a share link, Rita generates and stores the token.
 */
import crypto from "node:crypto";
import express from "express";
import { pool } from "../config/database.js";

const router = express.Router();

/**
 * GET /api/share/:conversationId
 *
 * Returns conversation title + messages for read-only sharing.
 * No auth middleware — access controlled by share_status + share_token.
 */
router.get("/:conversationId", async (req, res) => {
	try {
		const { conversationId } = req.params;
		const token = req.query.token as string | undefined;

		if (!conversationId) {
			return res.status(400).json({ error: "conversationId is required" });
		}

		// Fetch conversation with share metadata
		const conversationResult = await pool.query(
			`SELECT id, title, created_at, share_status, share_token
			 FROM conversations WHERE id = $1`,
			[conversationId],
		);

		if (conversationResult.rows.length === 0) {
			return res.status(404).json({ error: "Conversation not found" });
		}

		const conversation = conversationResult.rows[0];
		const shareStatus = conversation.share_status || "private";

		// Access control based on share_status
		if (shareStatus === "private") {
			return res.status(403).json({ error: "This conversation is not shared" });
		}

		if (shareStatus === "token") {
			if (!token) {
				return res
					.status(403)
					.json({ error: "Token required for this shared conversation" });
			}
			if (token !== conversation.share_token) {
				return res.status(403).json({ error: "Invalid share token" });
			}
		}

		// shareStatus === 'public' → no token needed

		// Fetch messages ordered chronologically
		const messagesResult = await pool.query(
			`SELECT id, role, message, metadata, response_group_id, created_at
			 FROM messages
			 WHERE conversation_id = $1
			 ORDER BY created_at ASC, id ASC`,
			[conversationId],
		);

		return res.json({
			conversation: {
				id: conversation.id,
				title: conversation.title,
				created_at: conversation.created_at,
			},
			messages: messagesResult.rows,
		});
	} catch (error) {
		console.error("[share] Error fetching shared conversation:", error);
		return res.status(500).json({ error: "Internal server error" });
	}
});

/**
 * POST /api/share/:conversationId/enable
 *
 * Enable sharing for a conversation. Generates a share token.
 * Called by Actions Platform when user clicks "Share".
 *
 * Body: { mode: "public" | "token" }
 * Returns: { shareUrl, shareToken? }
 */
router.post("/:conversationId/enable", async (req, res) => {
	try {
		const { conversationId } = req.params;
		const { mode = "public" } = req.body || {};

		if (!["public", "token"].includes(mode)) {
			return res
				.status(400)
				.json({ error: "mode must be 'public' or 'token'" });
		}

		const shareToken =
			mode === "token" ? crypto.randomBytes(32).toString("hex") : null;

		const result = await pool.query(
			`UPDATE conversations
			 SET share_status = $1, share_token = $2
			 WHERE id = $3
			 RETURNING id, share_status, share_token`,
			[mode, shareToken, conversationId],
		);

		if (result.rows.length === 0) {
			return res.status(404).json({ error: "Conversation not found" });
		}

		const baseUrl = `${req.protocol}://${req.get("host")}`;
		const shareUrl =
			mode === "token"
				? `${baseUrl}/jarvis/${conversationId}?token=${shareToken}`
				: `${baseUrl}/jarvis/${conversationId}`;

		return res.json({
			shareUrl,
			shareToken: shareToken || undefined,
			shareStatus: mode,
		});
	} catch (error) {
		console.error("[share] Error enabling share:", error);
		return res.status(500).json({ error: "Internal server error" });
	}
});

/**
 * POST /api/share/:conversationId/disable
 *
 * Disable sharing for a conversation. Revokes the share token.
 */
router.post("/:conversationId/disable", async (req, res) => {
	try {
		const { conversationId } = req.params;

		const result = await pool.query(
			`UPDATE conversations
			 SET share_status = 'private', share_token = NULL
			 WHERE id = $1
			 RETURNING id`,
			[conversationId],
		);

		if (result.rows.length === 0) {
			return res.status(404).json({ error: "Conversation not found" });
		}

		return res.json({ success: true });
	} catch (error) {
		console.error("[share] Error disabling share:", error);
		return res.status(500).json({ error: "Internal server error" });
	}
});

export default router;
