/**
 * Cluster Types
 * Type definitions for autopilot clusters and tickets
 */

/**
 * KB status values for clusters
 */
export type KBStatus = "PENDING" | "FOUND" | "GAP";

/**
 * Rita status values for tickets
 */
export type RitaStatus = "NEEDS_RESPONSE" | "COMPLETED";

/**
 * Cluster configuration
 */
export interface ClusterConfig {
	auto_respond?: boolean;
	auto_populate?: boolean;
}

/**
 * Cluster entity from database
 */
export interface Cluster {
	id: string;
	organization_id: string;
	model_id: string;
	name: string;
	subcluster_name: string | null;
	config: ClusterConfig;
	kb_status: KBStatus;
	created_at: Date;
	updated_at: Date;
}

/**
 * Cluster details response with counts
 */
export interface ClusterDetails extends Cluster {
	kb_articles_count: number;
	ticket_count: number;
	open_count: number;
	historical_ticket_count: number;
}

/**
 * Cluster list item with ticket counts (for dashboard)
 */
export interface ClusterListItem {
	id: string;
	name: string;
	subcluster_name: string | null;
	kb_status: KBStatus;
	config: ClusterConfig;
	ticket_count: number;
	needs_response_count: number;
	created_at: Date;
	updated_at: Date;
}

/**
 * Sort options for cluster list
 */
export type ClusterSortOption = "volume" | "automation" | "recent";

/**
 * Period filter for ticket counts
 */
export type PeriodFilter = "last30" | "last90" | "last6months" | "lastyear";

/**
 * Query options for listing clusters
 */
export interface ClusterListQueryOptions {
	sort?: ClusterSortOption;
	period?: PeriodFilter;
	limit?: number;
	offset?: number;
	kbStatus?: KBStatus;
	search?: string;
}

/**
 * Ticket entity from database
 */
export interface Ticket {
	id: string;
	organization_id: string;
	cluster_id: string | null;
	data_source_connection_id: string | null;
	external_id: string;
	subject: string;
	description: string | null;
	external_status: string;
	cluster_text: string | null;
	rita_status: RitaStatus;
	source_metadata: Record<string, any>;
	requester: string | null;
	assigned_to: string | null;
	priority: string | null;
	created_at: Date;
	updated_at: Date;
}

/**
 * Cursor-based pagination info (for cluster list)
 */
export interface CursorPaginationInfo {
	next_cursor: string | null;
	has_more: boolean;
}

/**
 * Offset-based pagination info (for cluster tickets)
 */
export interface OffsetPaginationInfo {
	total: number;
	limit: number;
	offset: number;
	has_more: boolean;
}

/**
 * Totals for cluster list response
 */
export interface ClusterTotals {
	total_clusters: number;
	total_tickets: number;
	total_automated_tickets: number;
}

/**
 * Sort options for cluster tickets
 */
export type TicketSortOption = "created_at" | "external_id" | "subject";

/**
 * Sort direction
 */
export type SortDirection = "asc" | "desc";

/**
 * Query options for cluster tickets
 */
export interface ClusterTicketsQueryOptions {
	tab?: "needs_response" | "completed";
	offset?: number;
	limit?: number;
	search?: string;
	sort?: TicketSortOption;
	sort_dir?: SortDirection;
	source?: string;
	priority?: string;
	external_status?: string;
}

/**
 * Response for GET /api/clusters/:id/details
 */
export interface ClusterDetailsResponse {
	data: ClusterDetails;
}

/**
 * Response for GET /api/clusters/:id/tickets
 */
export interface ClusterTicketsResponse {
	data: Ticket[];
	pagination: OffsetPaginationInfo;
}

/**
 * Historical ticket entity from database
 * Slim version of Ticket focused on knowledge generation
 */
export interface HistoricalTicket {
	id: string;
	organization_id: string;
	cluster_id: string | null;
	data_source_connection_id: string | null;
	external_id: string;
	subject: string;
	description: string | null;
	resolution: string | null;
	external_status: string;
	source_metadata: Record<string, any>;
	closed_at: Date;
	created_at: Date;
	updated_at: Date;
}

/**
 * KB article from blob_metadata
 */
export interface KbArticle {
	id: string;
	filename: string;
	file_size: number;
	mime_type: string;
	status: string;
	created_at: Date;
	updated_at: Date;
}

/**
 * Response for GET /api/clusters/:id/kb-articles
 */
export interface ClusterKbArticlesResponse {
	data: KbArticle[];
}

/**
 * Response for POST /api/clusters/:id/generate-knowledge
 */
export interface GenerateKnowledgeResponse {
	generation_id: string;
}

// ============================================================================
// Cluster Events (RabbitMQ consumer messages)
// ============================================================================

/**
 * Knowledge article generated by external platform
 */
export interface KnowledgeGeneratedEvent {
	type: "knowledge_generated";
	tenant_id: string;
	user_id: string;
	cluster_id: string;
	generation_id: string;
	status: "success" | "failed";
	content?: string;
	filename?: string;
	format?: "markdown" | "text";
	error_message?: string;
}

/**
 * Discriminated union for cluster.events queue messages
 * Add new event types here as the cluster domain grows
 */
export type ClusterEventMessage = KnowledgeGeneratedEvent;
