/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I | undefined, U>
	: ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
	[x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ActivityContexts {
	activity_id: number;
	conversation_id: string;
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	organization_id: string;
}

export interface AuditLogs {
	action: string;
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	metadata: Json | null;
	organization_id: string;
	resource_id: string | null;
	resource_type: string;
	user_id: string | null;
}

export interface BlobMetadata {
	blob_id: string;
	created_at: Generated<Timestamp>;
	file_size: number;
	filename: string;
	id: Generated<string>;
	metadata: Generated<Json>;
	mime_type: string;
	organization_id: string;
	processed_markdown: string | null;
	/**
	 * Data source origin: manual (uploaded), confluence, servicenow, sharepoint, websearch. NULL if unknown.
	 */
	source: string | null;
	status: Generated<string>;
	updated_at: Generated<Timestamp>;
	user_id: string;
}

export interface Blobs {
	blob_id: Generated<string>;
	data: Buffer;
	digest: string;
}

export interface ClusterKbLinks {
	blob_metadata_id: string;
	cluster_id: string;
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	organization_id: string;
}

export interface Clusters {
	config: Generated<Json | null>;
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	/**
	 * Knowledge base coverage: PENDING (checking), FOUND (has KB), GAP (missing KB)
	 */
	kb_status: Generated<string | null>;
	/**
	 * ML model that generated this cluster (required)
	 */
	model_id: string;
	name: string;
	organization_id: string;
	/**
	 * Subcluster name (NULL = top-level cluster only)
	 */
	subcluster_name: string | null;
	updated_at: Generated<Timestamp | null>;
}

export interface Conversations {
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	organization_id: string;
	source: string | null;
	title: string;
	updated_at: Generated<Timestamp | null>;
	user_id: string;
}

export interface CredentialDelegationTokens {
	admin_email: string;
	connection_id: string | null;
	created_at: Generated<Timestamp | null>;
	created_by_user_id: string;
	credentials_received_at: Timestamp | null;
	credentials_verified_at: Timestamp | null;
	/**
	 * Unique token sent to IT admin for credential submission
	 */
	delegation_token: string;
	id: Generated<string>;
	/**
	 * ITSM connection type: servicenow_itsm, jira_itsm
	 */
	itsm_system_type: string;
	last_verification_error: string | null;
	organization_id: string;
	/**
	 * Token lifecycle: pending -> used -> verified (or expired/cancelled)
	 */
	status: Generated<string>;
	/**
	 * Non-sensitive settings submitted by IT admin (instance_url, username/email). Does not contain passwords/tokens.
	 */
	submitted_settings: Json | null;
	token_expires_at: Timestamp;
}

export interface DataSourceConnections {
	created_at: Generated<Timestamp | null>;
	created_by: string;
	description: string | null;
	/**
	 * Whether the data source is configured and active
	 */
	enabled: Generated<boolean | null>;
	id: Generated<string>;
	last_sync_at: Timestamp | null;
	/**
	 * Error message from last sync operation (cleared on successful sync)
	 */
	last_sync_error: string | null;
	/**
	 * Last sync result: NULL (never synced), completed, failed
	 */
	last_sync_status: string | null;
	/**
	 * Timestamp of last credential verification attempt
	 */
	last_verification_at: Timestamp | null;
	/**
	 * Error message from last verification attempt (cleared on successful verification)
	 */
	last_verification_error: string | null;
	/**
	 * JSONB with connection-type-specific options from last successful verification (e.g., {"spaces": "ENG,PROD", "sites": "confluence.company.com"})
	 */
	latest_options: Json | null;
	name: string;
	organization_id: string;
	/**
	 * JSONB settings specific to each data source type (no credentials)
	 */
	settings: Generated<Json | null>;
	/**
	 * Current operation status: idle (ready), verifying (checking credentials), syncing (in progress)
	 */
	status: Generated<string>;
	/**
	 * Data source type: confluence, servicenow, sharepoint, websearch
	 */
	type: string;
	updated_at: Generated<Timestamp | null>;
	updated_by: string;
}

export interface IngestionRuns {
	completed_at: Timestamp | null;
	created_at: Generated<Timestamp | null>;
	data_source_connection_id: string | null;
	error_message: string | null;
	id: Generated<string>;
	metadata: Generated<Json | null>;
	organization_id: string;
	records_failed: Generated<number | null>;
	records_processed: Generated<number | null>;
	/**
	 * User who triggered the sync (required - always user-initiated)
	 */
	started_by: string;
	status: Generated<string | null>;
	updated_at: Generated<Timestamp | null>;
}

export interface MessageProcessingFailures {
	created_at: Generated<Timestamp | null>;
	/**
	 * Detailed error message from processing failure
	 */
	error_message: string;
	/**
	 * Category of error (validation, timeout, database, etc.)
	 */
	error_type: string | null;
	id: Generated<string>;
	/**
	 * Maximum number of retry attempts allowed
	 */
	max_retries: Generated<number | null>;
	/**
	 * Unique identifier of the failed message
	 */
	message_id: string;
	/**
	 * Original message content as JSON
	 */
	message_payload: Json;
	/**
	 * When the next retry attempt should occur
	 */
	next_retry_at: Timestamp | null;
	/**
	 * When the message was originally received from the queue
	 */
	original_received_at: Timestamp;
	/**
	 * Current status: failed, retrying, dead_letter, resolved
	 */
	processing_status: Generated<string | null>;
	/**
	 * Name of the queue the message came from
	 */
	queue_name: string;
	/**
	 * Number of times processing has been retried
	 */
	retry_count: Generated<number | null>;
	/**
	 * UUID of the tenant associated with the message (NULL if tenant cannot be determined)
	 */
	tenant_id: string | null;
	updated_at: Generated<Timestamp | null>;
}

export interface Messages {
	conversation_id: string | null;
	created_at: Generated<Timestamp | null>;
	document_ids: string[] | null;
	error_message: string | null;
	id: Generated<string>;
	message: string;
	/**
	 * JSONB metadata for rich message types (reasoning, sources, tasks, files)
	 */
	metadata: Json | null;
	organization_id: string;
	processed_at: Timestamp | null;
	response: string | null;
	response_content: string | null;
	/**
	 * Groups related messages together for cohesive AI responses
	 */
	response_group_id: string | null;
	role: string;
	sent_at: Timestamp | null;
	status: Generated<string | null>;
	user_id: string;
}

export interface MigrationHistory {
	executed_at: Generated<Timestamp | null>;
	id: Generated<number>;
	migration_name: string;
}

export interface MlModels {
	/**
	 * Whether this is the active model for the org (one per org, enforced by WF)
	 */
	active: Generated<boolean>;
	created_at: Generated<Timestamp | null>;
	/**
	 * Model ID from ML team system (used in API calls)
	 */
	external_model_id: string;
	id: Generated<string>;
	metadata: Generated<Json | null>;
	model_name: string;
	organization_id: string;
	training_end_date: Timestamp | null;
	training_start_date: Timestamp | null;
	updated_at: Generated<Timestamp | null>;
}

export interface OrganizationMembers {
	is_active: Generated<boolean>;
	joined_at: Generated<Timestamp | null>;
	organization_id: string;
	role: Generated<string>;
	user_id: string;
}

export interface Organizations {
	created_at: Generated<Timestamp | null>;
	id: Generated<string>;
	name: string;
	updated_at: Generated<Timestamp | null>;
}

export interface PendingInvitations {
	accepted_at: Timestamp | null;
	created_at: Generated<Timestamp | null>;
	email: string;
	id: Generated<string>;
	/**
	 * Unique token sent via email for invitation acceptance
	 */
	invitation_token: string;
	invited_by_user_id: string;
	organization_id: string;
	/**
	 * Current status of the invitation (pending, accepted, expired, cancelled, failed)
	 */
	status: Generated<string>;
	token_expires_at: Timestamp;
}

export interface PendingUsers {
	company: string;
	created_at: Generated<Timestamp | null>;
	email: string;
	first_name: string;
	id: Generated<string>;
	last_name: string;
	/**
	 * Tracks user verification state: pending (not verified), verified (email verified, awaiting first login)
	 */
	status: Generated<string>;
	/**
	 * Expiration time for the verification token
	 */
	token_expires_at: Timestamp;
	/**
	 * Timestamp when user accepted Terms of Service during signup
	 */
	tos_accepted_at: Timestamp | null;
	/**
	 * Unique token sent via email for account verification
	 */
	verification_token: string;
}

export interface PhantomCitations {
	/**
	 * The blob_id that was requested but not found (legacy format, backward compatibility)
	 */
	blob_id: string;
	/**
	 * The blob_metadata.id that was requested but not found (new format, preferred)
	 */
	blob_metadata_id: string | null;
	created_at: Generated<Timestamp>;
	/**
	 * When this phantom citation was first encountered
	 */
	first_seen: Generated<Timestamp>;
	id: Generated<string>;
	/**
	 * When this phantom citation was most recently encountered
	 */
	last_seen: Generated<Timestamp>;
	/**
	 * Number of times this phantom citation has been requested
	 */
	occurrence_count: Generated<number>;
	organization_id: string;
	updated_at: Generated<Timestamp>;
	user_id: string;
}

export interface RagWebhookFailures {
	created_at: Generated<Timestamp | null>;
	id: Generated<number>;
	last_error: string | null;
	max_retries: Generated<number | null>;
	next_retry_at: Timestamp | null;
	payload: Json;
	retry_count: Generated<number | null>;
	status: Generated<string | null>;
	tenant_id: string;
	updated_at: Generated<Timestamp | null>;
	webhook_type: string;
}

export interface SyncCancellationRequests {
	/**
	 * Data source connection to cancel
	 */
	connection_id: string;
	/**
	 * Type of connection (confluence, servicenow, etc)
	 */
	connection_type: string;
	/**
	 * Connection URL from settings
	 */
	connection_url: string | null;
	created_at: Generated<Timestamp | null>;
	/**
	 * Email from connection settings
	 */
	email: string | null;
	id: Generated<string>;
	/**
	 * Processing status: pending, processing, completed
	 */
	status: Generated<string>;
	/**
	 * Organization that owns the connection
	 */
	tenant_id: string;
	updated_at: Generated<Timestamp | null>;
	/**
	 * User who requested the cancellation
	 */
	user_id: string | null;
}

export interface Tickets {
	/**
	 * NULL until classification workflow assigns cluster
	 */
	cluster_id: string | null;
	/**
	 * Text used for classification (set by ingestion, used by classification workflow)
	 */
	cluster_text: string | null;
	created_at: Generated<Timestamp | null>;
	data_source_connection_id: string | null;
	/**
	 * Ticket ID from ITSM system (Jira/ServiceNow)
	 */
	external_id: string;
	external_status: string;
	id: Generated<string>;
	organization_id: string;
	/**
	 * Rita processing status: NEEDS_RESPONSE or COMPLETED
	 */
	rita_status: Generated<string | null>;
	source_metadata: Generated<Json | null>;
	subject: string;
	updated_at: Generated<Timestamp | null>;
}

export interface UserProfiles {
	active_organization_id: string | null;
	created_at: Generated<Timestamp | null>;
	email: string | null;
	/**
	 * User first name from Keycloak JWT token (given_name claim)
	 */
	first_name: string | null;
	/**
	 * The unique subject identifier (sub) from Keycloak.
	 */
	keycloak_id: string | null;
	/**
	 * User last name from Keycloak JWT token (family_name claim)
	 */
	last_name: string | null;
	/**
	 * Last profile update timestamp
	 */
	updated_at: Generated<Timestamp | null>;
	user_id: string;
}

export interface DB {
	activity_contexts: ActivityContexts;
	audit_logs: AuditLogs;
	blob_metadata: BlobMetadata;
	blobs: Blobs;
	cluster_kb_links: ClusterKbLinks;
	clusters: Clusters;
	conversations: Conversations;
	credential_delegation_tokens: CredentialDelegationTokens;
	data_source_connections: DataSourceConnections;
	ingestion_runs: IngestionRuns;
	message_processing_failures: MessageProcessingFailures;
	messages: Messages;
	migration_history: MigrationHistory;
	ml_models: MlModels;
	organization_members: OrganizationMembers;
	organizations: Organizations;
	pending_invitations: PendingInvitations;
	pending_users: PendingUsers;
	phantom_citations: PhantomCitations;
	rag_webhook_failures: RagWebhookFailures;
	sync_cancellation_requests: SyncCancellationRequests;
	tickets: Tickets;
	user_profiles: UserProfiles;
}
