import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	discoverSidebar: [
		{
			type: "doc",
			id: "README",
			label: "Overview",
		},
		{
			type: "category",
			label: "Actors",
			link: {
				type: "generated-index",
				title: "Actors",
				description: "Users who interact with the application.",
			},
			items: [{ type: "autogenerated", dirName: "actors" }],
		},
		{
			type: "category",
			label: "Views",
			link: {
				type: "generated-index",
				title: "Views",
				description: "Pages and screens in the application.",
			},
			items: [{ type: "autogenerated", dirName: "views" }],
		},
		{
			type: "category",
			label: "Journeys",
			link: {
				type: "generated-index",
				title: "Journeys",
				description:
					"User workflows defined by product. Empty until product defines them.",
			},
			items: [{ type: "autogenerated", dirName: "journeys" }],
			collapsed: true,
		},
		{
			type: "category",
			label: "Constraints",
			link: {
				type: "generated-index",
				title: "Constraints",
				description: "Rules applied to actors for views.",
			},
			items: [{ type: "autogenerated", dirName: "constraints" }],
			collapsed: true,
		},
		{
			type: "category",
			label: "Engineering",
			link: {
				type: "generated-index",
				title: "Engineering Reference",
				description:
					"Code entities — services, hooks, components. Auto-generated from source.",
			},
			items: [{ type: "autogenerated", dirName: "engineering" }],
			collapsed: true,
		},
		{
			type: "category",
			label: "Reports",
			link: { type: "generated-index", title: "Reports" },
			items: [{ type: "autogenerated", dirName: "generated" }],
			collapsed: true,
		},
	],
};

export default sidebars;
