import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	discoverSidebar: [
		{
			type: "doc",
			id: "README",
			label: "Overview",
		},
		{
			type: "category",
			label: "Journeys",
			link: { type: "generated-index", title: "Journeys" },
			items: [{ type: "autogenerated", dirName: "journeys" }],
		},
		{
			type: "category",
			label: "Actors",
			link: { type: "generated-index", title: "Actors" },
			items: [{ type: "autogenerated", dirName: "actors" }],
		},
		{
			type: "category",
			label: "Views",
			link: { type: "generated-index", title: "Views" },
			items: [{ type: "autogenerated", dirName: "views" }],
		},
		{
			type: "category",
			label: "Constraints",
			link: { type: "generated-index", title: "Constraints" },
			items: [{ type: "autogenerated", dirName: "constraints" }],
		},
		{
			type: "category",
			label: "Reports",
			link: { type: "generated-index", title: "Reports" },
			items: [{ type: "autogenerated", dirName: "generated" }],
		},
	],
};

export default sidebars;
